### ISSUE TITLE
No asm crash?

### ISSUE THREAD

**Issue by ChocoPuppy** [NOVA-Team/NOVA-Core#185]
When I install the mod with artillics I get this crash, from what I could see it required ASM which wasn't on my computer so I installed it but when I run the ASM jar it did nothing so here is the crash log (I have also looked about a bit and heard of no other problems sorry if I missed that it's already solves though)

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 06/09/15 15:40
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: nova.core.wrapper.mc17.NovaMinecraftPreloader
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:345)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: nova.core.wrapper.mc17.NovaMinecraftPreloader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:340)
	... 11 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at openmods.asm.VisitorHelper.apply(VisitorHelper.java:32)
	at openmods.core.OpenModsClassTransformer.applyIncludes(OpenModsClassTransformer.java:234)
	at openmods.core.OpenModsClassTransformer.transform(OpenModsClassTransformer.java:227)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 350499592 bytes (334 MB) / 442499072 bytes (422 MB) up to 2796552192 bytes (2667 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3000M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 6 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
		Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
		appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
		CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
		NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 560 SE/PCIe/SSE2'
```

**Comment by RX14** [comment]
ASM is bundled with forge, and you can't install it simply by running the jar anyways, so please don't try. This seems to be a strange inter-mod compatibility issue, let me look into it.

**Comment by RX14** [comment]
It seems that OpenModsLib is using the ASM4 api, which crashes when a java 8 class is reached, I shall create an issue on their side to see if it can be fixed, thanks for reporting.

**Comment by RX14** [comment]
See the above linked issue for updates.

**Comment by RX14** [comment]
Please can you update your OpenModsLib to the version downloadable [here](http://www.openmods.info:8080/job/OpenModsLib/393/artifact/build/libs/OpenModsLib-1.7.10-0.8-snapshot-393.jar) and try again.

**Comment by boq** [comment]
Please note that this version will be incompatible with released OpenPeripheral (if present).

**Comment by RX14** [comment]
If it crashes somewhere else, we can at least know we fixed the problem :p

**Comment by ChocoPuppy** [comment]
It has been fixed by following the problems mentioned, my next crash however is on artillicts end so I will now proceed to bother them, sorry for the trouble and missing the other issue

**Comment by RX14** [comment]
Thanks for the bug report!
